version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PSG-Admin-panel-DEMO
    ports:
      - "3030:80"
    environment:
      - VITE_BASE_API_URL=${VITE_BASE_API_URL}